### ISSUE TITLE
Error when downloading images from the British Library

### ISSUE THREAD

**Issue by Mennaruuk** [balta2ar/manuscript-dl#4]
Traceback (most recent call last):
  File "C:\Users\Menna\Downloads\bl.uk.py", line 423, in <module>
    sys.exit(main(args))
  File "C:\Users\Menna\Downloads\bl.uk.py", line 401, in main
    download_manuscript(args.pages,
  File "C:\Users\Menna\Downloads\bl.uk.py", line 392, in download_manuscript
    download_pages(resolution, base_dir, manuscript, pages)
  File "C:\Users\Menna\Downloads\bl.uk.py", line 358, in download_pages
    concatenate_page(base_dir, manuscript, page, columns, rows)
  File "C:\Users\Menna\Downloads\bl.uk.py", line 299, in concatenate_page
    call(cmd)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by aharonium** [comment]
What steps did you take to solve this issue @Mennaruuk? (I see the same error.) The issue, at least for me, seems to do with not being able to install the cropresize python module which has a PIL dependency (unresolved by Pillow, alas).

**Comment by Mennaruuk** [comment]
@aharonium It may very well be a problem with cropresize. TBH I didn't have the time to debug this. I used an existing tool called [dezoomify](http://www.bl.uk/manuscripts/Viewer.aspx?ref=add_ms_24686_f136r) to download my transcript of interest. If the site doesn't work, [try the CLI tool](https://github.com/lovasoa/dezoomify-rs).
